// Generated by https://quicktype.io

export interface Empleados {
  id?:             number;
  nombre_empleado: string;
  rut_empleado:    string;
  email:           string;
  empresa:         string;
}
export interface FormEmpleados {
  id?:             number;
  nombre_empleado?:string;
  rut_empleado?:   string;
  email?:          string;
  empresa?:        string;
}
